//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WillMvcHomework1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class 客戶聯絡人
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public int 客戶Id { get; set; }
        [Required(ErrorMessage = "職稱不得為空")]
        public string 職稱 { get; set; }
        [Required(ErrorMessage = "姓名不得為空")]
        public string 姓名 { get; set; }
        [Required(ErrorMessage = "Email不得為空")]
        [Remote("IsMailAvailable", "Validation", AdditionalFields = "客戶Id,Id", ErrorMessage = "Email已重覆")]
        [RegularExpression(@"^([a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4})*$", ErrorMessage = "Email格式不正確")]
        public string Email { get; set; }
        [RegularExpression(@"\d{4}-\d{6}", ErrorMessage = "手機號碼格式不正確")]
        public string 手機 { get; set; }
        public string 電話 { get; set; }
        public bool 是否刪除 { get; set; }
    
        public virtual 客戶資料 客戶資料 { get; set; }
    }
}
