//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WillMvcHomework1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class 客戶銀行資訊
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public int 客戶Id { get; set; }
        [Required(ErrorMessage = "銀行名稱不得為空")]
        public string 銀行名稱 { get; set; }
        [Required(ErrorMessage = "銀行代碼不得為空")]
        public int 銀行代碼 { get; set; }
        public Nullable<int> 分行代碼 { get; set; }
        [Required(ErrorMessage = "帳戶名稱不得為空")]
        public string 帳戶名稱 { get; set; }
        [Required(ErrorMessage = "帳戶號碼不得為空")]
        public string 帳戶號碼 { get; set; }
        public bool 是否刪除 { get; set; }
    
        public virtual 客戶資料 客戶資料 { get; set; }
    }
}
